package wt;

/**
 * This class provides the properties that are needed to be loaded from
 * language-dependent XML files.

    Author:	Richard McKenna
    Author:	?
    Version:	1.0
 */
public enum LanguageProperty {
    ADD_ELEMENT_ERROR_MESSAGE,
    ADD_ELEMENT_ERROR_TITLE,
    
    ATTRIBUTE_UPDATE_ERROR_MESSAGE,
    ATTRIBUTE_UPDATE_ERROR_TITLE,
    
    CSS_EXPORT_ERROR_MESSAGE,
    CSS_EXPORT_ERROR_TITLE,

    ILLEGAL_NODE_REMOVAL_ERROR_MESSAGE, 
    ILLEGAL_NODE_REMOVAL_ERROR_TITLE,
    
    ILLEGAL_NODE_CUT_ERROR_MESSAGE,
    ILLEGAL_NODE_CUT_ERROR_TITLE,
    
    ILLEGAL_NODE_COPY_ERROR_MESSAGE,
    ILLEGAL_NODE_COPY_ERROR_TITLE,
    
    ILLEGAL_NODE_PASTE_ERROR_MESSAGE,
    ILLEGAL_NODE_PASTE_ERROR_TITLE,
    
    REMOVE_ELEMENT_ERROR_MESSAGE,
    REMOVE_ELEMENT_ERROR_TITLE,

    REMOVE_ELEMENT_ICON,
    REMOVE_ELEMENT_TOOLTIP,
    REMOVE_ELEMENT_MESSAGE,

    TAG_LOADING_ERROR_TITLE,
    TAG_LOADING_ERROR_MESSAGE,
        
    TEMP_PAGE_LOAD_ERROR_MESSAGE,
    TEMP_PAGE_LOAD_ERROR_TITLE,

    UPDATE_ERROR_MESSAGE,
    UPDATE_ERROR_TITLE
}